// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ggarcia209/go-aws-v2/v2/gosns (interfaces: SNSLogic)
//
// Generated by this command:
//
//	mockgen -destination=../mocks/gosnsmock/sns.go -package=gosnsmock . SNSLogic
//

// Package gosnsmock is a generated GoMock package.
package gosnsmock

import (
	context "context"
	reflect "reflect"

	gosns "github.com/ggarcia209/go-aws-v2/v2/gosns"
	gomock "go.uber.org/mock/gomock"
)

// MockSNSLogic is a mock of SNSLogic interface.
type MockSNSLogic struct {
	ctrl     *gomock.Controller
	recorder *MockSNSLogicMockRecorder
	isgomock struct{}
}

// MockSNSLogicMockRecorder is the mock recorder for MockSNSLogic.
type MockSNSLogicMockRecorder struct {
	mock *MockSNSLogic
}

// NewMockSNSLogic creates a new mock instance.
func NewMockSNSLogic(ctrl *gomock.Controller) *MockSNSLogic {
	mock := &MockSNSLogic{ctrl: ctrl}
	mock.recorder = &MockSNSLogicMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSNSLogic) EXPECT() *MockSNSLogicMockRecorder {
	return m.recorder
}

// CreateTopic mocks base method.
func (m *MockSNSLogic) CreateTopic(ctx context.Context, name string) (*gosns.CreateTopicResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTopic", ctx, name)
	ret0, _ := ret[0].(*gosns.CreateTopicResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTopic indicates an expected call of CreateTopic.
func (mr *MockSNSLogicMockRecorder) CreateTopic(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTopic", reflect.TypeOf((*MockSNSLogic)(nil).CreateTopic), ctx, name)
}

// ListTopics mocks base method.
func (m *MockSNSLogic) ListTopics(ctx context.Context) (*gosns.ListTopicsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTopics", ctx)
	ret0, _ := ret[0].(*gosns.ListTopicsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTopics indicates an expected call of ListTopics.
func (mr *MockSNSLogicMockRecorder) ListTopics(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTopics", reflect.TypeOf((*MockSNSLogic)(nil).ListTopics), ctx)
}

// Publish mocks base method.
func (m *MockSNSLogic) Publish(ctx context.Context, msgStr, topicArn string) (*gosns.PublishResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", ctx, msgStr, topicArn)
	ret0, _ := ret[0].(*gosns.PublishResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Publish indicates an expected call of Publish.
func (mr *MockSNSLogicMockRecorder) Publish(ctx, msgStr, topicArn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockSNSLogic)(nil).Publish), ctx, msgStr, topicArn)
}

// Subscribe mocks base method.
func (m *MockSNSLogic) Subscribe(ectx context.Context, ndpoint, protocol, topicArn string) (*gosns.SubscribeResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Subscribe", ectx, ndpoint, protocol, topicArn)
	ret0, _ := ret[0].(*gosns.SubscribeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Subscribe indicates an expected call of Subscribe.
func (mr *MockSNSLogicMockRecorder) Subscribe(ectx, ndpoint, protocol, topicArn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Subscribe", reflect.TypeOf((*MockSNSLogic)(nil).Subscribe), ectx, ndpoint, protocol, topicArn)
}
