// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ggarcia209/go-aws-v2/v2/gos3 (interfaces: S3Logic)
//
// Generated by this command:
//
//	mockgen -destination=../mocks/gos3mock/s3.go -package=gos3mock . S3Logic
//

// Package gos3mock is a generated GoMock package.
package gos3mock

import (
	context "context"
	reflect "reflect"

	gos3 "github.com/ggarcia209/go-aws-v2/v2/gos3"
	gomock "go.uber.org/mock/gomock"
)

// MockS3Logic is a mock of S3Logic interface.
type MockS3Logic struct {
	ctrl     *gomock.Controller
	recorder *MockS3LogicMockRecorder
	isgomock struct{}
}

// MockS3LogicMockRecorder is the mock recorder for MockS3Logic.
type MockS3LogicMockRecorder struct {
	mock *MockS3Logic
}

// NewMockS3Logic creates a new mock instance.
func NewMockS3Logic(ctrl *gomock.Controller) *MockS3Logic {
	mock := &MockS3Logic{ctrl: ctrl}
	mock.recorder = &MockS3LogicMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockS3Logic) EXPECT() *MockS3LogicMockRecorder {
	return m.recorder
}

// CheckIfObjectExists mocks base method.
func (m *MockS3Logic) CheckIfObjectExists(ctx context.Context, req gos3.GetFileRequest) (*gos3.ObjectExistsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckIfObjectExists", ctx, req)
	ret0, _ := ret[0].(*gos3.ObjectExistsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckIfObjectExists indicates an expected call of CheckIfObjectExists.
func (mr *MockS3LogicMockRecorder) CheckIfObjectExists(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckIfObjectExists", reflect.TypeOf((*MockS3Logic)(nil).CheckIfObjectExists), ctx, req)
}

// DeleteFile mocks base method.
func (m *MockS3Logic) DeleteFile(ctx context.Context, bucket, key string, versionId *string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFile", ctx, bucket, key, versionId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteFile indicates an expected call of DeleteFile.
func (mr *MockS3LogicMockRecorder) DeleteFile(ctx, bucket, key, versionId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFile", reflect.TypeOf((*MockS3Logic)(nil).DeleteFile), ctx, bucket, key, versionId)
}

// GetObject mocks base method.
func (m *MockS3Logic) GetObject(ctx context.Context, req gos3.GetFileRequest) (*gos3.GetObjectResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetObject", ctx, req)
	ret0, _ := ret[0].(*gos3.GetObjectResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetObject indicates an expected call of GetObject.
func (mr *MockS3LogicMockRecorder) GetObject(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetObject", reflect.TypeOf((*MockS3Logic)(nil).GetObject), ctx, req)
}

// GetPresignedURL mocks base method.
func (m *MockS3Logic) GetPresignedURL(ctx context.Context, req gos3.GetPresignedUrlRequest) (*gos3.GetPresignedUrlResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPresignedURL", ctx, req)
	ret0, _ := ret[0].(*gos3.GetPresignedUrlResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPresignedURL indicates an expected call of GetPresignedURL.
func (mr *MockS3LogicMockRecorder) GetPresignedURL(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPresignedURL", reflect.TypeOf((*MockS3Logic)(nil).GetPresignedURL), ctx, req)
}

// HeadObject mocks base method.
func (m *MockS3Logic) HeadObject(ctx context.Context, req gos3.GetFileRequest) (*gos3.HeadObjectResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HeadObject", ctx, req)
	ret0, _ := ret[0].(*gos3.HeadObjectResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HeadObject indicates an expected call of HeadObject.
func (mr *MockS3LogicMockRecorder) HeadObject(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HeadObject", reflect.TypeOf((*MockS3Logic)(nil).HeadObject), ctx, req)
}

// UploadFile mocks base method.
func (m *MockS3Logic) UploadFile(ctx context.Context, req gos3.UploadFileRequest) (*gos3.UploadFileResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadFile", ctx, req)
	ret0, _ := ret[0].(*gos3.UploadFileResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadFile indicates an expected call of UploadFile.
func (mr *MockS3LogicMockRecorder) UploadFile(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadFile", reflect.TypeOf((*MockS3Logic)(nil).UploadFile), ctx, req)
}
