// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ggarcia209/go-aws-v2/v2/gos3 (interfaces: S3PresignClientAPI)
//
// Generated by this command:
//
//	mockgen -destination=./s3_presign_client_test.go -package=gos3 . S3PresignClientAPI
//

// Package gos3 is a generated GoMock package.
package gos3

import (
	context "context"
	reflect "reflect"

	v4 "github.com/aws/aws-sdk-go-v2/aws/signer/v4"
	s3 "github.com/aws/aws-sdk-go-v2/service/s3"
	gomock "go.uber.org/mock/gomock"
)

// MockS3PresignClientAPI is a mock of S3PresignClientAPI interface.
type MockS3PresignClientAPI struct {
	ctrl     *gomock.Controller
	recorder *MockS3PresignClientAPIMockRecorder
	isgomock struct{}
}

// MockS3PresignClientAPIMockRecorder is the mock recorder for MockS3PresignClientAPI.
type MockS3PresignClientAPIMockRecorder struct {
	mock *MockS3PresignClientAPI
}

// NewMockS3PresignClientAPI creates a new mock instance.
func NewMockS3PresignClientAPI(ctrl *gomock.Controller) *MockS3PresignClientAPI {
	mock := &MockS3PresignClientAPI{ctrl: ctrl}
	mock.recorder = &MockS3PresignClientAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockS3PresignClientAPI) EXPECT() *MockS3PresignClientAPIMockRecorder {
	return m.recorder
}

// PresignGetObject mocks base method.
func (m *MockS3PresignClientAPI) PresignGetObject(ctx context.Context, params *s3.GetObjectInput, optFns ...func(*s3.PresignOptions)) (*v4.PresignedHTTPRequest, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PresignGetObject", varargs...)
	ret0, _ := ret[0].(*v4.PresignedHTTPRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PresignGetObject indicates an expected call of PresignGetObject.
func (mr *MockS3PresignClientAPIMockRecorder) PresignGetObject(ctx, params any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PresignGetObject", reflect.TypeOf((*MockS3PresignClientAPI)(nil).PresignGetObject), varargs...)
}

// PresignPutObject mocks base method.
func (m *MockS3PresignClientAPI) PresignPutObject(ctx context.Context, params *s3.PutObjectInput, optFns ...func(*s3.PresignOptions)) (*v4.PresignedHTTPRequest, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PresignPutObject", varargs...)
	ret0, _ := ret[0].(*v4.PresignedHTTPRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PresignPutObject indicates an expected call of PresignPutObject.
func (mr *MockS3PresignClientAPIMockRecorder) PresignPutObject(ctx, params any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PresignPutObject", reflect.TypeOf((*MockS3PresignClientAPI)(nil).PresignPutObject), varargs...)
}
