// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ggarcia209/go-aws-v2/v2/gosqs (interfaces: SQSQueuesClientAPI)
//
// Generated by this command:
//
//	mockgen -destination=./queues_client_api_test.go -package=gosqs . SQSQueuesClientAPI
//

// Package gosqs is a generated GoMock package.
package gosqs

import (
	context "context"
	reflect "reflect"

	sqs "github.com/aws/aws-sdk-go-v2/service/sqs"
	gomock "go.uber.org/mock/gomock"
)

// MockSQSQueuesClientAPI is a mock of SQSQueuesClientAPI interface.
type MockSQSQueuesClientAPI struct {
	ctrl     *gomock.Controller
	recorder *MockSQSQueuesClientAPIMockRecorder
	isgomock struct{}
}

// MockSQSQueuesClientAPIMockRecorder is the mock recorder for MockSQSQueuesClientAPI.
type MockSQSQueuesClientAPIMockRecorder struct {
	mock *MockSQSQueuesClientAPI
}

// NewMockSQSQueuesClientAPI creates a new mock instance.
func NewMockSQSQueuesClientAPI(ctrl *gomock.Controller) *MockSQSQueuesClientAPI {
	mock := &MockSQSQueuesClientAPI{ctrl: ctrl}
	mock.recorder = &MockSQSQueuesClientAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSQSQueuesClientAPI) EXPECT() *MockSQSQueuesClientAPIMockRecorder {
	return m.recorder
}

// CreateQueue mocks base method.
func (m *MockSQSQueuesClientAPI) CreateQueue(ctx context.Context, params *sqs.CreateQueueInput, optFns ...func(*sqs.Options)) (*sqs.CreateQueueOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateQueue", varargs...)
	ret0, _ := ret[0].(*sqs.CreateQueueOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateQueue indicates an expected call of CreateQueue.
func (mr *MockSQSQueuesClientAPIMockRecorder) CreateQueue(ctx, params any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateQueue", reflect.TypeOf((*MockSQSQueuesClientAPI)(nil).CreateQueue), varargs...)
}

// DeleteQueue mocks base method.
func (m *MockSQSQueuesClientAPI) DeleteQueue(ctx context.Context, params *sqs.DeleteQueueInput, optFns ...func(*sqs.Options)) (*sqs.DeleteQueueOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteQueue", varargs...)
	ret0, _ := ret[0].(*sqs.DeleteQueueOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteQueue indicates an expected call of DeleteQueue.
func (mr *MockSQSQueuesClientAPIMockRecorder) DeleteQueue(ctx, params any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteQueue", reflect.TypeOf((*MockSQSQueuesClientAPI)(nil).DeleteQueue), varargs...)
}

// GetQueueUrl mocks base method.
func (m *MockSQSQueuesClientAPI) GetQueueUrl(ctx context.Context, params *sqs.GetQueueUrlInput, optFns ...func(*sqs.Options)) (*sqs.GetQueueUrlOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetQueueUrl", varargs...)
	ret0, _ := ret[0].(*sqs.GetQueueUrlOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetQueueUrl indicates an expected call of GetQueueUrl.
func (mr *MockSQSQueuesClientAPIMockRecorder) GetQueueUrl(ctx, params any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetQueueUrl", reflect.TypeOf((*MockSQSQueuesClientAPI)(nil).GetQueueUrl), varargs...)
}

// PurgeQueue mocks base method.
func (m *MockSQSQueuesClientAPI) PurgeQueue(ctx context.Context, params *sqs.PurgeQueueInput, optFns ...func(*sqs.Options)) (*sqs.PurgeQueueOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PurgeQueue", varargs...)
	ret0, _ := ret[0].(*sqs.PurgeQueueOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PurgeQueue indicates an expected call of PurgeQueue.
func (mr *MockSQSQueuesClientAPIMockRecorder) PurgeQueue(ctx, params any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PurgeQueue", reflect.TypeOf((*MockSQSQueuesClientAPI)(nil).PurgeQueue), varargs...)
}
