// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ggarcia209/go-aws-v2/v2/gosm (interfaces: SecretsManagerLogic)
//
// Generated by this command:
//
//	mockgen -destination=../mocks/gosmmock/secrets_manager.go -package=gosmmock . SecretsManagerLogic
//

// Package gosmmock is a generated GoMock package.
package gosmmock

import (
	context "context"
	reflect "reflect"

	gosm "github.com/ggarcia209/go-aws-v2/v2/gosm"
	gomock "go.uber.org/mock/gomock"
)

// MockSecretsManagerLogic is a mock of SecretsManagerLogic interface.
type MockSecretsManagerLogic struct {
	ctrl     *gomock.Controller
	recorder *MockSecretsManagerLogicMockRecorder
	isgomock struct{}
}

// MockSecretsManagerLogicMockRecorder is the mock recorder for MockSecretsManagerLogic.
type MockSecretsManagerLogicMockRecorder struct {
	mock *MockSecretsManagerLogic
}

// NewMockSecretsManagerLogic creates a new mock instance.
func NewMockSecretsManagerLogic(ctrl *gomock.Controller) *MockSecretsManagerLogic {
	mock := &MockSecretsManagerLogic{ctrl: ctrl}
	mock.recorder = &MockSecretsManagerLogicMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSecretsManagerLogic) EXPECT() *MockSecretsManagerLogicMockRecorder {
	return m.recorder
}

// GetSecret mocks base method.
func (m *MockSecretsManagerLogic) GetSecret(ctx context.Context, key string) (*gosm.GetSecretResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSecret", ctx, key)
	ret0, _ := ret[0].(*gosm.GetSecretResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSecret indicates an expected call of GetSecret.
func (mr *MockSecretsManagerLogicMockRecorder) GetSecret(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSecret", reflect.TypeOf((*MockSecretsManagerLogic)(nil).GetSecret), ctx, key)
}
