// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ggarcia209/go-aws-v2/v2/goses (interfaces: SESLogic)
//
// Generated by this command:
//
//	mockgen -destination=../mocks/gosesmock/ses.go -package=gosesmock . SESLogic
//

// Package gosesmock is a generated GoMock package.
package gosesmock

import (
	context "context"
	reflect "reflect"

	goses "github.com/ggarcia209/go-aws-v2/v2/goses"
	gomock "go.uber.org/mock/gomock"
)

// MockSESLogic is a mock of SESLogic interface.
type MockSESLogic struct {
	ctrl     *gomock.Controller
	recorder *MockSESLogicMockRecorder
	isgomock struct{}
}

// MockSESLogicMockRecorder is the mock recorder for MockSESLogic.
type MockSESLogicMockRecorder struct {
	mock *MockSESLogic
}

// NewMockSESLogic creates a new mock instance.
func NewMockSESLogic(ctrl *gomock.Controller) *MockSESLogic {
	mock := &MockSESLogic{ctrl: ctrl}
	mock.recorder = &MockSESLogicMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSESLogic) EXPECT() *MockSESLogicMockRecorder {
	return m.recorder
}

// ListVerifiedIdentities mocks base method.
func (m *MockSESLogic) ListVerifiedIdentities(ctx context.Context) (*goses.ListVerifiedIdentitiesResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListVerifiedIdentities", ctx)
	ret0, _ := ret[0].(*goses.ListVerifiedIdentitiesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListVerifiedIdentities indicates an expected call of ListVerifiedIdentities.
func (mr *MockSESLogicMockRecorder) ListVerifiedIdentities(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListVerifiedIdentities", reflect.TypeOf((*MockSESLogic)(nil).ListVerifiedIdentities), ctx)
}

// SendEmail mocks base method.
func (m *MockSESLogic) SendEmail(ctx context.Context, params goses.SendEmailParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendEmail", ctx, params)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendEmail indicates an expected call of SendEmail.
func (mr *MockSESLogicMockRecorder) SendEmail(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendEmail", reflect.TypeOf((*MockSESLogic)(nil).SendEmail), ctx, params)
}
