// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ggarcia209/go-aws-v2/v2/gosqs (interfaces: MessagesLogic)
//
// Generated by this command:
//
//	mockgen -destination=../mocks/gosqsmock/messages.go -package=gosqsmock . MessagesLogic
//

// Package gosqsmock is a generated GoMock package.
package gosqsmock

import (
	context "context"
	reflect "reflect"

	gosqs "github.com/ggarcia209/go-aws-v2/v2/gosqs"
	gomock "go.uber.org/mock/gomock"
)

// MockMessagesLogic is a mock of MessagesLogic interface.
type MockMessagesLogic struct {
	ctrl     *gomock.Controller
	recorder *MockMessagesLogicMockRecorder
	isgomock struct{}
}

// MockMessagesLogicMockRecorder is the mock recorder for MockMessagesLogic.
type MockMessagesLogicMockRecorder struct {
	mock *MockMessagesLogic
}

// NewMockMessagesLogic creates a new mock instance.
func NewMockMessagesLogic(ctrl *gomock.Controller) *MockMessagesLogic {
	mock := &MockMessagesLogic{ctrl: ctrl}
	mock.recorder = &MockMessagesLogicMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessagesLogic) EXPECT() *MockMessagesLogicMockRecorder {
	return m.recorder
}

// ChangeMessageVisibilityBatch mocks base method.
func (m *MockMessagesLogic) ChangeMessageVisibilityBatch(ctx context.Context, req gosqs.BatchUpdateVisibilityTimeoutRequest) (*gosqs.BatchUpdateVisibilityTimeoutResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangeMessageVisibilityBatch", ctx, req)
	ret0, _ := ret[0].(*gosqs.BatchUpdateVisibilityTimeoutResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ChangeMessageVisibilityBatch indicates an expected call of ChangeMessageVisibilityBatch.
func (mr *MockMessagesLogicMockRecorder) ChangeMessageVisibilityBatch(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangeMessageVisibilityBatch", reflect.TypeOf((*MockMessagesLogic)(nil).ChangeMessageVisibilityBatch), ctx, req)
}

// DeleteMessage mocks base method.
func (m *MockMessagesLogic) DeleteMessage(ctx context.Context, url, handle string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMessage", ctx, url, handle)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteMessage indicates an expected call of DeleteMessage.
func (mr *MockMessagesLogicMockRecorder) DeleteMessage(ctx, url, handle any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMessage", reflect.TypeOf((*MockMessagesLogic)(nil).DeleteMessage), ctx, url, handle)
}

// DeleteMessageBatch mocks base method.
func (m *MockMessagesLogic) DeleteMessageBatch(ctx context.Context, req gosqs.DeleteMessageBatchRequest) (*gosqs.DeleteMessageBatchResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMessageBatch", ctx, req)
	ret0, _ := ret[0].(*gosqs.DeleteMessageBatchResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteMessageBatch indicates an expected call of DeleteMessageBatch.
func (mr *MockMessagesLogicMockRecorder) DeleteMessageBatch(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMessageBatch", reflect.TypeOf((*MockMessagesLogic)(nil).DeleteMessageBatch), ctx, req)
}

// ReceiveMessage mocks base method.
func (m *MockMessagesLogic) ReceiveMessage(ctx context.Context, options gosqs.RecMsgOptions) (*gosqs.ReceiveMessageResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReceiveMessage", ctx, options)
	ret0, _ := ret[0].(*gosqs.ReceiveMessageResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReceiveMessage indicates an expected call of ReceiveMessage.
func (mr *MockMessagesLogicMockRecorder) ReceiveMessage(ctx, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReceiveMessage", reflect.TypeOf((*MockMessagesLogic)(nil).ReceiveMessage), ctx, options)
}

// SendMessage mocks base method.
func (m *MockMessagesLogic) SendMessage(ctx context.Context, options gosqs.SendMsgOptions) (*gosqs.SendMsgResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMessage", ctx, options)
	ret0, _ := ret[0].(*gosqs.SendMsgResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendMessage indicates an expected call of SendMessage.
func (mr *MockMessagesLogicMockRecorder) SendMessage(ctx, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMessage", reflect.TypeOf((*MockMessagesLogic)(nil).SendMessage), ctx, options)
}
