// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ggarcia209/go-aws-v2/v2/gosqs (interfaces: QueuesLogic)
//
// Generated by this command:
//
//	mockgen -destination=../mocks/gosqsmock/queues.go -package=gosqsmock . QueuesLogic
//

// Package gosqsmock is a generated GoMock package.
package gosqsmock

import (
	context "context"
	reflect "reflect"

	gosqs "github.com/ggarcia209/go-aws-v2/v2/gosqs"
	gomock "go.uber.org/mock/gomock"
)

// MockQueuesLogic is a mock of QueuesLogic interface.
type MockQueuesLogic struct {
	ctrl     *gomock.Controller
	recorder *MockQueuesLogicMockRecorder
	isgomock struct{}
}

// MockQueuesLogicMockRecorder is the mock recorder for MockQueuesLogic.
type MockQueuesLogicMockRecorder struct {
	mock *MockQueuesLogic
}

// NewMockQueuesLogic creates a new mock instance.
func NewMockQueuesLogic(ctrl *gomock.Controller) *MockQueuesLogic {
	mock := &MockQueuesLogic{ctrl: ctrl}
	mock.recorder = &MockQueuesLogicMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQueuesLogic) EXPECT() *MockQueuesLogicMockRecorder {
	return m.recorder
}

// CreateQueue mocks base method.
func (m *MockQueuesLogic) CreateQueue(ctx context.Context, name string, options gosqs.QueueOptions, tags map[string]string) (*gosqs.CreateQueueResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateQueue", ctx, name, options, tags)
	ret0, _ := ret[0].(*gosqs.CreateQueueResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateQueue indicates an expected call of CreateQueue.
func (mr *MockQueuesLogicMockRecorder) CreateQueue(ctx, name, options, tags any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateQueue", reflect.TypeOf((*MockQueuesLogic)(nil).CreateQueue), ctx, name, options, tags)
}

// DeleteQueue mocks base method.
func (m *MockQueuesLogic) DeleteQueue(ctx context.Context, url string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteQueue", ctx, url)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteQueue indicates an expected call of DeleteQueue.
func (mr *MockQueuesLogicMockRecorder) DeleteQueue(ctx, url any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteQueue", reflect.TypeOf((*MockQueuesLogic)(nil).DeleteQueue), ctx, url)
}

// GetQueueURL mocks base method.
func (m *MockQueuesLogic) GetQueueURL(ctx context.Context, name string) (*gosqs.GetQueueUrlResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetQueueURL", ctx, name)
	ret0, _ := ret[0].(*gosqs.GetQueueUrlResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetQueueURL indicates an expected call of GetQueueURL.
func (mr *MockQueuesLogicMockRecorder) GetQueueURL(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetQueueURL", reflect.TypeOf((*MockQueuesLogic)(nil).GetQueueURL), ctx, name)
}

// PurgeQueue mocks base method.
func (m *MockQueuesLogic) PurgeQueue(ctx context.Context, url string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PurgeQueue", ctx, url)
	ret0, _ := ret[0].(error)
	return ret0
}

// PurgeQueue indicates an expected call of PurgeQueue.
func (mr *MockQueuesLogicMockRecorder) PurgeQueue(ctx, url any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PurgeQueue", reflect.TypeOf((*MockQueuesLogic)(nil).PurgeQueue), ctx, url)
}
