// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ggarcia209/go-aws-v2/v2/godynamo (interfaces: DynamoDBTablesClientAPI)
//
// Generated by this command:
//
//	mockgen -destination=./tables_client_api_test.go -package=godynamo . DynamoDBTablesClientAPI
//

// Package godynamo is a generated GoMock package.
package godynamo

import (
	context "context"
	reflect "reflect"

	dynamodb "github.com/aws/aws-sdk-go-v2/service/dynamodb"
	gomock "go.uber.org/mock/gomock"
)

// MockDynamoDBTablesClientAPI is a mock of DynamoDBTablesClientAPI interface.
type MockDynamoDBTablesClientAPI struct {
	ctrl     *gomock.Controller
	recorder *MockDynamoDBTablesClientAPIMockRecorder
	isgomock struct{}
}

// MockDynamoDBTablesClientAPIMockRecorder is the mock recorder for MockDynamoDBTablesClientAPI.
type MockDynamoDBTablesClientAPIMockRecorder struct {
	mock *MockDynamoDBTablesClientAPI
}

// NewMockDynamoDBTablesClientAPI creates a new mock instance.
func NewMockDynamoDBTablesClientAPI(ctrl *gomock.Controller) *MockDynamoDBTablesClientAPI {
	mock := &MockDynamoDBTablesClientAPI{ctrl: ctrl}
	mock.recorder = &MockDynamoDBTablesClientAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDynamoDBTablesClientAPI) EXPECT() *MockDynamoDBTablesClientAPIMockRecorder {
	return m.recorder
}

// CreateTable mocks base method.
func (m *MockDynamoDBTablesClientAPI) CreateTable(ctx context.Context, params *dynamodb.CreateTableInput, optFns ...func(*dynamodb.Options)) (*dynamodb.CreateTableOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateTable", varargs...)
	ret0, _ := ret[0].(*dynamodb.CreateTableOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTable indicates an expected call of CreateTable.
func (mr *MockDynamoDBTablesClientAPIMockRecorder) CreateTable(ctx, params any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTable", reflect.TypeOf((*MockDynamoDBTablesClientAPI)(nil).CreateTable), varargs...)
}

// DeleteTable mocks base method.
func (m *MockDynamoDBTablesClientAPI) DeleteTable(ctx context.Context, params *dynamodb.DeleteTableInput, optFns ...func(*dynamodb.Options)) (*dynamodb.DeleteTableOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteTable", varargs...)
	ret0, _ := ret[0].(*dynamodb.DeleteTableOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteTable indicates an expected call of DeleteTable.
func (mr *MockDynamoDBTablesClientAPIMockRecorder) DeleteTable(ctx, params any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTable", reflect.TypeOf((*MockDynamoDBTablesClientAPI)(nil).DeleteTable), varargs...)
}

// ListTables mocks base method.
func (m *MockDynamoDBTablesClientAPI) ListTables(ctx context.Context, params *dynamodb.ListTablesInput, optFns ...func(*dynamodb.Options)) (*dynamodb.ListTablesOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListTables", varargs...)
	ret0, _ := ret[0].(*dynamodb.ListTablesOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTables indicates an expected call of ListTables.
func (mr *MockDynamoDBTablesClientAPIMockRecorder) ListTables(ctx, params any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTables", reflect.TypeOf((*MockDynamoDBTablesClientAPI)(nil).ListTables), varargs...)
}
