// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ggarcia209/go-aws-v2/v2/godynamo (interfaces: DynamoDBTransactionsClientAPI)
//
// Generated by this command:
//
//	mockgen -destination=./transactions_client_api_test.go -package=godynamo . DynamoDBTransactionsClientAPI
//

// Package godynamo is a generated GoMock package.
package godynamo

import (
	context "context"
	reflect "reflect"

	dynamodb "github.com/aws/aws-sdk-go-v2/service/dynamodb"
	gomock "go.uber.org/mock/gomock"
)

// MockDynamoDBTransactionsClientAPI is a mock of DynamoDBTransactionsClientAPI interface.
type MockDynamoDBTransactionsClientAPI struct {
	ctrl     *gomock.Controller
	recorder *MockDynamoDBTransactionsClientAPIMockRecorder
	isgomock struct{}
}

// MockDynamoDBTransactionsClientAPIMockRecorder is the mock recorder for MockDynamoDBTransactionsClientAPI.
type MockDynamoDBTransactionsClientAPIMockRecorder struct {
	mock *MockDynamoDBTransactionsClientAPI
}

// NewMockDynamoDBTransactionsClientAPI creates a new mock instance.
func NewMockDynamoDBTransactionsClientAPI(ctrl *gomock.Controller) *MockDynamoDBTransactionsClientAPI {
	mock := &MockDynamoDBTransactionsClientAPI{ctrl: ctrl}
	mock.recorder = &MockDynamoDBTransactionsClientAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDynamoDBTransactionsClientAPI) EXPECT() *MockDynamoDBTransactionsClientAPIMockRecorder {
	return m.recorder
}

// TransactWriteItems mocks base method.
func (m *MockDynamoDBTransactionsClientAPI) TransactWriteItems(ctx context.Context, params *dynamodb.TransactWriteItemsInput, optFns ...func(*dynamodb.Options)) (*dynamodb.TransactWriteItemsOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "TransactWriteItems", varargs...)
	ret0, _ := ret[0].(*dynamodb.TransactWriteItemsOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TransactWriteItems indicates an expected call of TransactWriteItems.
func (mr *MockDynamoDBTransactionsClientAPIMockRecorder) TransactWriteItems(ctx, params any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TransactWriteItems", reflect.TypeOf((*MockDynamoDBTransactionsClientAPI)(nil).TransactWriteItems), varargs...)
}
