// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ggarcia209/go-aws-v2/v2/godynamo (interfaces: QueriesLogic)
//
// Generated by this command:
//
//	mockgen -destination=../mocks/godynamomock/queries.go -package=godynamomock . QueriesLogic
//

// Package godynamomock is a generated GoMock package.
package godynamomock

import (
	context "context"
	reflect "reflect"

	godynamo "github.com/ggarcia209/go-aws-v2/v2/godynamo"
	gomock "go.uber.org/mock/gomock"
)

// MockQueriesLogic is a mock of QueriesLogic interface.
type MockQueriesLogic struct {
	ctrl     *gomock.Controller
	recorder *MockQueriesLogicMockRecorder
	isgomock struct{}
}

// MockQueriesLogicMockRecorder is the mock recorder for MockQueriesLogic.
type MockQueriesLogicMockRecorder struct {
	mock *MockQueriesLogic
}

// NewMockQueriesLogic creates a new mock instance.
func NewMockQueriesLogic(ctrl *gomock.Controller) *MockQueriesLogic {
	mock := &MockQueriesLogic{ctrl: ctrl}
	mock.recorder = &MockQueriesLogicMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQueriesLogic) EXPECT() *MockQueriesLogicMockRecorder {
	return m.recorder
}

// BatchGet mocks base method.
func (m *MockQueriesLogic) BatchGet(ctx context.Context, tableName string, queries []*godynamo.Query, expr godynamo.Expression) ([]godynamo.QueryRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchGet", ctx, tableName, queries, expr)
	ret0, _ := ret[0].([]godynamo.QueryRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BatchGet indicates an expected call of BatchGet.
func (mr *MockQueriesLogicMockRecorder) BatchGet(ctx, tableName, queries, expr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchGet", reflect.TypeOf((*MockQueriesLogic)(nil).BatchGet), ctx, tableName, queries, expr)
}

// BatchWriteCreate mocks base method.
func (m *MockQueriesLogic) BatchWriteCreate(ctx context.Context, tableName string, items []any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchWriteCreate", ctx, tableName, items)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchWriteCreate indicates an expected call of BatchWriteCreate.
func (mr *MockQueriesLogicMockRecorder) BatchWriteCreate(ctx, tableName, items any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchWriteCreate", reflect.TypeOf((*MockQueriesLogic)(nil).BatchWriteCreate), ctx, tableName, items)
}

// BatchWriteDelete mocks base method.
func (m *MockQueriesLogic) BatchWriteDelete(ctx context.Context, tableName string, queries []*godynamo.Query) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchWriteDelete", ctx, tableName, queries)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchWriteDelete indicates an expected call of BatchWriteDelete.
func (mr *MockQueriesLogicMockRecorder) BatchWriteDelete(ctx, tableName, queries any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchWriteDelete", reflect.TypeOf((*MockQueriesLogic)(nil).BatchWriteDelete), ctx, tableName, queries)
}

// CreateItem mocks base method.
func (m *MockQueriesLogic) CreateItem(ctx context.Context, item any, tableName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateItem", ctx, item, tableName)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateItem indicates an expected call of CreateItem.
func (mr *MockQueriesLogicMockRecorder) CreateItem(ctx, item, tableName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateItem", reflect.TypeOf((*MockQueriesLogic)(nil).CreateItem), ctx, item, tableName)
}

// DeleteItem mocks base method.
func (m *MockQueriesLogic) DeleteItem(ctx context.Context, query *godynamo.Query, tableName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteItem", ctx, query, tableName)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteItem indicates an expected call of DeleteItem.
func (mr *MockQueriesLogicMockRecorder) DeleteItem(ctx, query, tableName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteItem", reflect.TypeOf((*MockQueriesLogic)(nil).DeleteItem), ctx, query, tableName)
}

// GetItem mocks base method.
func (m *MockQueriesLogic) GetItem(ctx context.Context, params godynamo.GetItemParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetItem", ctx, params)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetItem indicates an expected call of GetItem.
func (mr *MockQueriesLogicMockRecorder) GetItem(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetItem", reflect.TypeOf((*MockQueriesLogic)(nil).GetItem), ctx, params)
}

// QueryItems mocks base method.
func (m *MockQueriesLogic) QueryItems(ctx context.Context, params godynamo.QueryItemsParams) (*godynamo.QueryResults, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryItems", ctx, params)
	ret0, _ := ret[0].(*godynamo.QueryResults)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryItems indicates an expected call of QueryItems.
func (mr *MockQueriesLogicMockRecorder) QueryItems(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryItems", reflect.TypeOf((*MockQueriesLogic)(nil).QueryItems), ctx, params)
}

// ScanItems mocks base method.
func (m *MockQueriesLogic) ScanItems(ctx context.Context, params godynamo.QueryItemsParams) (*godynamo.ScanResults, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ScanItems", ctx, params)
	ret0, _ := ret[0].(*godynamo.ScanResults)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ScanItems indicates an expected call of ScanItems.
func (mr *MockQueriesLogicMockRecorder) ScanItems(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ScanItems", reflect.TypeOf((*MockQueriesLogic)(nil).ScanItems), ctx, params)
}

// UpdateItem mocks base method.
func (m *MockQueriesLogic) UpdateItem(ctx context.Context, query *godynamo.Query, tableName string, expr godynamo.Expression) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateItem", ctx, query, tableName, expr)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateItem indicates an expected call of UpdateItem.
func (mr *MockQueriesLogicMockRecorder) UpdateItem(ctx, query, tableName, expr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateItem", reflect.TypeOf((*MockQueriesLogic)(nil).UpdateItem), ctx, query, tableName, expr)
}
