// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ggarcia209/go-aws-v2/v2/godynamo (interfaces: TablesLogic)
//
// Generated by this command:
//
//	mockgen -destination=../mocks/godynamomock/tables.go -package=godynamomock . TablesLogic
//

// Package godynamomock is a generated GoMock package.
package godynamomock

import (
	context "context"
	reflect "reflect"

	godynamo "github.com/ggarcia209/go-aws-v2/v2/godynamo"
	gomock "go.uber.org/mock/gomock"
)

// MockTablesLogic is a mock of TablesLogic interface.
type MockTablesLogic struct {
	ctrl     *gomock.Controller
	recorder *MockTablesLogicMockRecorder
	isgomock struct{}
}

// MockTablesLogicMockRecorder is the mock recorder for MockTablesLogic.
type MockTablesLogicMockRecorder struct {
	mock *MockTablesLogic
}

// NewMockTablesLogic creates a new mock instance.
func NewMockTablesLogic(ctrl *gomock.Controller) *MockTablesLogic {
	mock := &MockTablesLogic{ctrl: ctrl}
	mock.recorder = &MockTablesLogicMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTablesLogic) EXPECT() *MockTablesLogicMockRecorder {
	return m.recorder
}

// CreateTable mocks base method.
func (m *MockTablesLogic) CreateTable(ctx context.Context, table *godynamo.Table) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTable", ctx, table)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateTable indicates an expected call of CreateTable.
func (mr *MockTablesLogicMockRecorder) CreateTable(ctx, table any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTable", reflect.TypeOf((*MockTablesLogic)(nil).CreateTable), ctx, table)
}

// DeleteTable mocks base method.
func (m *MockTablesLogic) DeleteTable(ctx context.Context, tableName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTable", ctx, tableName)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTable indicates an expected call of DeleteTable.
func (mr *MockTablesLogicMockRecorder) DeleteTable(ctx, tableName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTable", reflect.TypeOf((*MockTablesLogic)(nil).DeleteTable), ctx, tableName)
}

// ListTables mocks base method.
func (m *MockTablesLogic) ListTables(ctx context.Context, params godynamo.ListTableParams) ([]string, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTables", ctx, params)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListTables indicates an expected call of ListTables.
func (mr *MockTablesLogicMockRecorder) ListTables(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTables", reflect.TypeOf((*MockTablesLogic)(nil).ListTables), ctx, params)
}
