// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ggarcia209/go-aws-v2/v2/godynamo (interfaces: TransactionsLogic)
//
// Generated by this command:
//
//	mockgen -destination=../mocks/godynamomock/transactions.go -package=godynamomock . TransactionsLogic
//

// Package godynamomock is a generated GoMock package.
package godynamomock

import (
	context "context"
	reflect "reflect"

	godynamo "github.com/ggarcia209/go-aws-v2/v2/godynamo"
	gomock "go.uber.org/mock/gomock"
)

// MockTransactionsLogic is a mock of TransactionsLogic interface.
type MockTransactionsLogic struct {
	ctrl     *gomock.Controller
	recorder *MockTransactionsLogicMockRecorder
	isgomock struct{}
}

// MockTransactionsLogicMockRecorder is the mock recorder for MockTransactionsLogic.
type MockTransactionsLogicMockRecorder struct {
	mock *MockTransactionsLogic
}

// NewMockTransactionsLogic creates a new mock instance.
func NewMockTransactionsLogic(ctrl *gomock.Controller) *MockTransactionsLogic {
	mock := &MockTransactionsLogic{ctrl: ctrl}
	mock.recorder = &MockTransactionsLogicMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransactionsLogic) EXPECT() *MockTransactionsLogicMockRecorder {
	return m.recorder
}

// TxWrite mocks base method.
func (m *MockTransactionsLogic) TxWrite(ctx context.Context, items []godynamo.TransactionItem, requestToken string) ([]godynamo.TransactionItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TxWrite", ctx, items, requestToken)
	ret0, _ := ret[0].([]godynamo.TransactionItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TxWrite indicates an expected call of TxWrite.
func (mr *MockTransactionsLogicMockRecorder) TxWrite(ctx, items, requestToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TxWrite", reflect.TypeOf((*MockTransactionsLogic)(nil).TxWrite), ctx, items, requestToken)
}
