// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ggarcia209/go-aws-v2/v2/goses (interfaces: SESClientAPI)
//
// Generated by this command:
//
//	mockgen -destination=./ses_client_api_test.go -package=goses . SESClientAPI
//

// Package goses is a generated GoMock package.
package goses

import (
	context "context"
	reflect "reflect"

	sesv2 "github.com/aws/aws-sdk-go-v2/service/sesv2"
	gomock "go.uber.org/mock/gomock"
)

// MockSESClientAPI is a mock of SESClientAPI interface.
type MockSESClientAPI struct {
	ctrl     *gomock.Controller
	recorder *MockSESClientAPIMockRecorder
	isgomock struct{}
}

// MockSESClientAPIMockRecorder is the mock recorder for MockSESClientAPI.
type MockSESClientAPIMockRecorder struct {
	mock *MockSESClientAPI
}

// NewMockSESClientAPI creates a new mock instance.
func NewMockSESClientAPI(ctrl *gomock.Controller) *MockSESClientAPI {
	mock := &MockSESClientAPI{ctrl: ctrl}
	mock.recorder = &MockSESClientAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSESClientAPI) EXPECT() *MockSESClientAPIMockRecorder {
	return m.recorder
}

// ListEmailIdentities mocks base method.
func (m *MockSESClientAPI) ListEmailIdentities(ctx context.Context, params *sesv2.ListEmailIdentitiesInput, optFns ...func(*sesv2.Options)) (*sesv2.ListEmailIdentitiesOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListEmailIdentities", varargs...)
	ret0, _ := ret[0].(*sesv2.ListEmailIdentitiesOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListEmailIdentities indicates an expected call of ListEmailIdentities.
func (mr *MockSESClientAPIMockRecorder) ListEmailIdentities(ctx, params any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEmailIdentities", reflect.TypeOf((*MockSESClientAPI)(nil).ListEmailIdentities), varargs...)
}

// SendEmail mocks base method.
func (m *MockSESClientAPI) SendEmail(ctx context.Context, params *sesv2.SendEmailInput, optFns ...func(*sesv2.Options)) (*sesv2.SendEmailOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SendEmail", varargs...)
	ret0, _ := ret[0].(*sesv2.SendEmailOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendEmail indicates an expected call of SendEmail.
func (mr *MockSESClientAPIMockRecorder) SendEmail(ctx, params any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendEmail", reflect.TypeOf((*MockSESClientAPI)(nil).SendEmail), varargs...)
}
